import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics Textbook',
      items: [
        {
          type: 'category',
          label: 'Chapter 1: Introduction to Physical AI',
          items: [
            'physical-ai-book/intro/foundations',
            'physical-ai-book/intro/digital-to-embodied',
            'physical-ai-book/intro/humanoid-landscape',
            'physical-ai-book/intro/sensor-systems',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: ROS 2 Fundamentals',
          items: [
            {
              type: 'autogenerated',
              dirName: 'physical-ai-book/chapter2',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: Robot Simulation with Gazebo',
          items: [
            {
              type: 'autogenerated',
              dirName: 'physical-ai-book/chapter3',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chapter 4: NVIDIA Isaac Platform',
          items: [
            {
              type: 'autogenerated',
              dirName: 'physical-ai-book/chapter4',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chapter 5: Humanoid Robot Development',
          items: [
            {
              type: 'autogenerated',
              dirName: 'physical-ai-book/chapter5',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chapter 6: Conversational Robotics',
          items: [
            {
              type: 'autogenerated',
              dirName: 'physical-ai-book/chapter6',
            },
          ],
        },
      ],
    },
  ],
   
};

export default sidebars;
